name: Python Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: make recognize-os
    - name: Run Python script
      run: make python-venv-linux